snippets:
  - name: git
    keyword: g
    snippet: git
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git diff
    keyword: gd
    snippet: git diff
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'
  - name: git switch
    keyword: s
    snippet: switch
    context:
      lbuffer: 'git\s'
  - name: "null"
    keyword: "null"
    snippet: ">/dev/null 2>&1"
    context:
      lbuffer: '.+\s'

completions:
  - name: kill
    patterns:
      - "^kill( -9)? $"
    sourceCommand: "ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "Select a process to kill: "
    callback: "awk '{print $2}'"
